### ISSUE TITLE
Is this an error?

### ISSUE THREAD

**Issue by tandenawagner** [spielmanlab/introverse#24]
Sorry if I have made a mistake. I am a student trying to see your R lessons, but when I am installing the package it stops from an error that seems incorrect?

> -  building 'introverse_0.0.1.tar.gz'
>    
> Installing package into ‘***********’
> (as ‘lib’ is unspecified)
> ERROR: this R is version 3.6.1, package 'introverse' requires R >= 3.50
> Warning message:
> In i.p(...) :  installation of package ‘*************/introverse_0.0.1.tar.gz’ had non-zero exit status

If this is not an error on my end, I wanted to let you know.

**Comment by sjspielman** [comment]
This looks like it is probably an error on your end because this error suggests your R version is compatible. I can try to help figure out what's wrong, though! 
Can you tell me more about your setup by sending me the full output of the command `sessionInfo()` as it appears when you are trying to install introverse but getting the error?

**Comment by tandenawagner** [comment]
That's very kind of you -
Here is the sessionInfo() you mentioned:

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United
States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    tidyselect_1.1.1  R6_2.5.1
 rlang_0.4.11      fansi_0.4.2       dplyr_1.0.6
 [8] tools_3.6.1       pkgbuild_1.2.0    xfun_0.22         tinytex_0.31
 utf8_1.2.1        cli_2.5.0         DBI_1.1.1
[15] withr_2.4.2       ellipsis_0.3.2    remotes_2.4.0     rprojroot_2.0.2
  assertthat_0.2.1  tibble_3.1.1      lifecycle_1.0.0
[22] crayon_1.4.1      processx_3.5.2    purrr_0.3.4       callr_3.7.0
  vctrs_0.3.8       ps_1.6.0          curl_4.3.1
[29] glue_1.4.2        compiler_3.6.1    pillar_1.6.2
 prettyunits_1.1.1 generics_0.1.0    pkgconfig_2.0.3


I am guessing it has something to do with the tangled mess of packages I
have installed, but I do not know how to manage them. In trying to solve
this I just learned about unloading them. I tried to unload and update them
all which seems to have helped a little. I started with 14 warnings and
have seen 12, 8, and 3 warnings over the course of trying to troubleshoot
what is wrong.
I can run R as administrator but there are 00LOCK files that can't be
updated even with permissions.
I managed to "fix" all but 3 warnings by unloading all packages except base
R:

Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying
C:\Users\jacks\Documents\R\win-library\3.6\00LOCK\curl\libs\x64\curl.dll to
C:\Users\jacks\Documents\R\win-library\3.6\curl\libs\x64\curl.dll:
Permission denied
2: In i.p(...) : installation of package ‘tinytex’ had non-zero exit status
3: In i.p(...) :
  installation of package
‘C:/Users/jacks/AppData/Local/Temp/Rtmp8APPJf/filef7420222f51/introverse_0.0.1.tar.gz’
had non-zero exit status

And in order to run sessionInfo() I need some packages loaded and my
default set brings back 8 warnings.

1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying
C:\Users\jacks\Documents\R\win-library\3.6\00LOCK\utf8\libs\x64\utf8.dll to
C:\Users\jacks\Documents\R\win-library\3.6\utf8\libs\x64\utf8.dll:
Permission denied
2: \00LOCK\fansi\libs\x64\fansi.dll: Permission denied
3:\00LOCK\tibble\libs\x64\tibble.dll: Permission denied
4: \00LOCK\xfun\libs\x64\xfun.dll: Permission denied
5: \00LOCK\curl\libs\x64\curl.dll: Permission denied
6: \00LOCK\dplyr\libs\x64\dplyr.dll: Permission denied
7: In i.p(...) : installation of package ‘tinytex’ had non-zero exit status
8: In i.p(...) :
  installation of package
‘C:/Users/jacks/AppData/Local/Temp/RtmpWktWUI/file28c81fe0354c/introverse_0.0.1.tar.gz’
had non-zero exit status

Now that I know a little more about installing and running libraries I
would not mind a total reset. I think I could get it all back eventually.
But I don't really know where to start, and when I tried to do so once
before (months ago) it evidently didn't fix everything the way I hoped it
would.

No hard feelings if you don't get around to trying to solve my specific
combination of issues!
I don't understand what I am doing so there are maaaaany things that could
be the source of this, and it definitely is *my* end of things. 😵

Thanks for explaining the R error!
Tandena Wagner

**Comment by sjspielman** [comment]
Ok, so, the fact you have various tidyverse packages means that your computer likely has all the innards it needs to install packages. The `00LOCK` issues results when package installations fail and/or are interrupted. Not sure I can figure out exactly what the issue is from all this, but I would not recommend "unloading" anything. I recommend a totally clean slate by installing a much more recent version of R and associated dependencies. Note that when you install different versions of R, you will also need to re-install packages, so taking this step by step with a new R version may bring you to a place where you can use everything.

Try these steps:

1) From this website https://cran.r-project.org/bin/windows/, you need to install BOTH `base` and `Rtools`. Clicking on each link will bring you to a download page for each. I've also directly grabbed the download links for you: [base](https://cran.r-project.org/bin/windows/base/R-4.1.1-win.exe) and [Rtools](https://cran.r-project.org/bin/windows/Rtools/rtools40v2-x86_64.exe). You should be able to just click these and they'll download, and you can go through the installers from there.

2) This will get you set up with R version `4.1.1`, the latest release. Within the R Console now that you have the new version, run these back-to-back:
`install.packages("tidyverse")`
`remotes::install_github("introverse")`

This _should_ give you a working tidyverse and a working introverse. Note that at this point in introverse development, ALL package features are also available on the website (interactive exercises are not yet released, just the docs).

**Comment by tandenawagner** [comment]
Oof, thank you so much for walking me through what I need to do.
Knowing that it will be a clean slate if I do it that way is really
helpful. It's arduous when I don't know if it will be a difficult process
and then it might not even work.
I'll update later with how it turned out!

**Comment by tandenawagner** [comment]
Everything works beautifully and I have a fancy updated R version to boot!
Thanks for the assistance, and I look forward to the practice questions when you add them!


In case it's useful I recorded what I was interested in as I navved around:

`
install.packages("tidyverse")
install.packages("remotes")
remotes::install_github("introverse")
#error
remotes::install_github("spielmanlab/introverse")
library(introverse)
sessionInfo()
show_topics()
get_help("all")
get_help("str_count")
get_help("matches")
get_help("as_tibble")
get_help("%>%")
#Oh man I could have used the pipe explanation last week. I had to struggle through understanding it on my own 
# but you have all the examples right here.
get_help("fct_infreq")
get_help("setwd")

introverse::show_topics()
introverse::show_categories()
get_help("glue")
get_help("operators")
show_topics("operators")
get_help("assignment")
get_help("categories")
get_help("cat")
get_help("glimpse")
#Why would you use glimpse instead of head?
glimpse(msleep)
head(msleep)
get_help("levels")
# And I don't understand levels/categories/factors so this is going to be how I learn. 
factor<- as.factor(msleep$vore)
factor
levels(factor)
unique(factor)
show_topics
show_topics()
drop_na(unique(factor))
show_topics()
get_help("read_csv2")
get_help("length")
get_help("pull")
get_help("fct_rev")
get_help("fct_relevel")
#so levels is useful for ordering ggplot graphics and also for 
#rearranging tables so certain categories are in certain orders which
#are not necessarily alphabetical?
#I guess I get it and why that would be useful.
#most for arranging graphs though, that's been a problem before
show_topics()
get_help("case_when")
get_help("group_by")
head(carnivores)

carnivores %>% 
  group_by(genus) %>%
  summarize(brain_size = max(brainwt)) %>%
  ungroup()

carnivores %>% 
  group_by(genus) %>%
  summarize(brain_size = max(brainwt, na.rm=TRUE)) %>%
  ungroup()

#where did callhorhinus come from????
get_help("carnivores")
carnivores
#oh I thought head was 10 lines and that the tibble dimensions 
#described the original not the summary from head
`

**Comment by oliverbothe** [comment]
Hi, 
Just the quick information that I get the same error 

`Fehler: dies ist R Version 3.6.3, Paket 'introverse' benötigt R >= 3.50`

As I am not in a position to upgrade my R right now, I unfortunately cannot install the `introverse`. 

I admit that I have zero knowledge about building packages therefore the following is wild guessing: can the comparison 3.6.3 >= 3.50 ever be true as 50 is larger than 6?
